# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backup0.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1501, 794)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1081, 801))
        self.frame.setStyleSheet("#frame {\n"
"    background-color:#282c34;\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.left_top_block = QtWidgets.QLineEdit(self.frame)
        self.left_top_block.setEnabled(True)
        self.left_top_block.setGeometry(QtCore.QRect(90, 10, 211, 221))
        self.left_top_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.left_top_block.setObjectName("left_top_block")
        self.top_middle_block = QtWidgets.QLineEdit(self.frame)
        self.top_middle_block.setGeometry(QtCore.QRect(460, 10, 211, 221))
        self.top_middle_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.top_middle_block.setObjectName("top_middle_block")
        self.top_right_block = QtWidgets.QLineEdit(self.frame)
        self.top_right_block.setGeometry(QtCore.QRect(820, 10, 211, 221))
        self.top_right_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.top_right_block.setObjectName("top_right_block")
        self.middle_left_block = QtWidgets.QLineEdit(self.frame)
        self.middle_left_block.setGeometry(QtCore.QRect(90, 280, 211, 221))
        self.middle_left_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.middle_left_block.setObjectName("middle_left_block")
        self.middle_middle_block = QtWidgets.QLineEdit(self.frame)
        self.middle_middle_block.setGeometry(QtCore.QRect(460, 280, 211, 221))
        self.middle_middle_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.middle_middle_block.setObjectName("middle_middle_block")
        self.middle_right_block = QtWidgets.QLineEdit(self.frame)
        self.middle_right_block.setGeometry(QtCore.QRect(820, 280, 211, 221))
        self.middle_right_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.middle_right_block.setObjectName("middle_right_block")
        self.bot_left_block = QtWidgets.QLineEdit(self.frame)
        self.bot_left_block.setGeometry(QtCore.QRect(90, 550, 211, 221))
        self.bot_left_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.bot_left_block.setObjectName("bot_left_block")
        self.bot_middle_block = QtWidgets.QLineEdit(self.frame)
        self.bot_middle_block.setGeometry(QtCore.QRect(460, 550, 211, 221))
        self.bot_middle_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.bot_middle_block.setObjectName("bot_middle_block")
        self.bot_right_block = QtWidgets.QLineEdit(self.frame)
        self.bot_right_block.setGeometry(QtCore.QRect(820, 550, 211, 221))
        self.bot_right_block.setStyleSheet("QLineEdit {\n"
"    border:2px solid red;\n"
"    border-radius:100%;\n"
"    font-size:150px;\n"
"    padding-left:58px;\n"
"}")
        self.bot_right_block.setObjectName("bot_right_block")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 240, 1221, 16))
        self.line.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 520, 1081, 16))
        self.line_2.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(370, 0, 20, 791))
        self.line_3.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(750, 0, 16, 801))
        self.line_4.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setObjectName("line_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1080, 240, 421, 561))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background:#282c34;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(0, 0, 421, 16))
        self.line_5.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(1080, 0, 16, 801))
        self.line_7.setStyleSheet("QFrame {\n"
"    background-color:purple;\n"
"}")
        self.line_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setObjectName("line_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1100, 0, 171, 51))
        self.label.setStyleSheet("font-size:30px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1100, 60, 47, 31))
        self.label_2.setStyleSheet("font-size:40px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1210, 60, 101, 31))
        self.label_3.setStyleSheet("font-size:25px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1150, 50, 31, 51))
        self.label_4.setStyleSheet("font-size:30px;\n"
"color:red;")
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(1100, 110, 241, 16))
        self.frame_3.setStyleSheet("background-color:gray;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1100, 130, 171, 51))
        self.label_5.setStyleSheet("font-size:30px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1150, 180, 31, 51))
        self.label_6.setStyleSheet("font-size:30px;\n"
"color:red;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1100, 190, 47, 31))
        self.label_7.setStyleSheet("font-size:40px;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1210, 190, 101, 31))
        self.label_8.setStyleSheet("font-size:25px;")
        self.label_8.setObjectName("label_8")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(1340, 0, 16, 241))
        self.frame_4.setStyleSheet("background-color:gray;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Reset_Scores = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_Scores.setGeometry(QtCore.QRect(1370, 60, 101, 101))
        self.Reset_Scores.setStyleSheet("#Reset_Scores {\n"
"    font-size:16px;\n"
"    border:5px solid blue;\n"
"    border-radius:40px;\n"
"    background-color:black;\n"
"    color:white;\n"
"    \n"
"}")    
        self.Reset_Scores.setObjectName("Reset_Scores")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic Tac Toe"))
        self.label.setText(_translate("MainWindow", "Player_1 (X) :"))
        self.label_2.setText(_translate("MainWindow", "="))
        self.label_3.setText(_translate("MainWindow", "SCORE !"))
        self.label_4.setText(_translate("MainWindow", "25"))
        self.label_5.setText(_translate("MainWindow", "Player_2 (O) :"))
        self.label_6.setText(_translate("MainWindow", "25"))
        self.label_7.setText(_translate("MainWindow", "="))
        self.label_8.setText(_translate("MainWindow", "SCORE !"))
        self.Reset_Scores.setText(_translate("MainWindow", "Reset Scores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())