# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tic_tac_toe_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1150, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 731))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.player1_label = QtWidgets.QLabel(self.frame_2)
        self.player1_label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"\n"
"")
        self.player1_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.player1_label.setObjectName("player1_label")
        self.verticalLayout_8.addWidget(self.player1_label)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setEnabled(True)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 4)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xy11 = QtWidgets.QLabel(self.centralwidget)
        self.xy11.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy11.setText("")
        self.xy11.setAlignment(QtCore.Qt.AlignCenter)
        self.xy11.setObjectName("xy11")
        self.horizontalLayout_6.addWidget(self.xy11)
        self.xy12 = QtWidgets.QLabel(self.centralwidget)
        self.xy12.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy12.setText("")
        self.xy12.setAlignment(QtCore.Qt.AlignCenter)
        self.xy12.setObjectName("xy12")
        self.horizontalLayout_6.addWidget(self.xy12)
        self.xy13 = QtWidgets.QLabel(self.centralwidget)
        self.xy13.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy13.setText("")
        self.xy13.setAlignment(QtCore.Qt.AlignCenter)
        self.xy13.setObjectName("xy13")
        self.horizontalLayout_6.addWidget(self.xy13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xy21 = QtWidgets.QLabel(self.centralwidget)
        self.xy21.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy21.setText("")
        self.xy21.setAlignment(QtCore.Qt.AlignCenter)
        self.xy21.setObjectName("xy21")
        self.horizontalLayout_5.addWidget(self.xy21)
        self.xy22 = QtWidgets.QLabel(self.centralwidget)
        self.xy22.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy22.setText("")
        self.xy22.setAlignment(QtCore.Qt.AlignCenter)
        self.xy22.setObjectName("xy22")
        self.horizontalLayout_5.addWidget(self.xy22)
        self.xy23 = QtWidgets.QLabel(self.centralwidget)
        self.xy23.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy23.setText("")
        self.xy23.setAlignment(QtCore.Qt.AlignCenter)
        self.xy23.setObjectName("xy23")
        self.horizontalLayout_5.addWidget(self.xy23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.xy31 = QtWidgets.QLabel(self.centralwidget)
        self.xy31.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy31.setText("")
        self.xy31.setAlignment(QtCore.Qt.AlignCenter)
        self.xy31.setObjectName("xy31")
        self.horizontalLayout_4.addWidget(self.xy31)
        self.xy32 = QtWidgets.QLabel(self.centralwidget)
        self.xy32.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy32.setText("")
        self.xy32.setAlignment(QtCore.Qt.AlignCenter)
        self.xy32.setObjectName("xy32")
        self.horizontalLayout_4.addWidget(self.xy32)
        self.xy33 = QtWidgets.QLabel(self.centralwidget)
        self.xy33.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 65pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; \n"
"border-radius: 70px;\n"
"color: rgb(170, 255, 255);")
        self.xy33.setText("")
        self.xy33.setAlignment(QtCore.Qt.AlignCenter)
        self.xy33.setObjectName("xy33")
        self.horizontalLayout_4.addWidget(self.xy33)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.player2_label = QtWidgets.QLabel(self.frame)
        self.player2_label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border: 3px solid red; ")
        self.player2_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.player2_label.setObjectName("player2_label")
        self.verticalLayout_9.addWidget(self.player2_label)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 4)
        self.verticalLayout_7.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic Tac Toe"))
        self.player1_label.setText(_translate("MainWindow", "Player 1"))
        self.player2_label.setText(_translate("MainWindow", "Player 2"))
